"""Loading a saved conversation (`get_session_messages`) into the ConversationBuilder."""

from history_fakes import assistant_entry, user_entry

from claudio_maestro.conversation import ConversationBuilder


def test_text_tool_with_result_and_tool_without_result():
    entries = [
        user_entry("crie o arquivo"),
        assistant_entry({"type": "thinking", "thinking": "pensando", "signature": "x"}, "m1"),
        assistant_entry({"type": "text", "text": "Vou criar."}, "m1"),
        assistant_entry(
            {"type": "tool_use", "id": "t1", "name": "Write", "input": {"file_path": "a"}}, "m1"
        ),
        user_entry([{"type": "tool_result", "tool_use_id": "t1", "content": "ok"}]),
        assistant_entry({"type": "text", "text": "Pronto."}, "m2"),
        assistant_entry({"type": "tool_use", "id": "t2", "name": "Bash", "input": {}}, "m2"),
    ]
    builder = ConversationBuilder()

    builder.load_history(entries)

    items = builder.snapshot()
    assert [i["type"] for i in items] == ["user", "thinking", "text", "tool", "text", "tool"]
    assert items[0]["text"] == "crie o arquivo"
    assert items[1]["text"] == "pensando" and items[1]["streaming"] is False
    assert items[2]["id"] == "m1:1"
    tool = items[3]
    assert tool["tool_use_id"] == "t1"
    assert tool["result"] == {"content": "ok", "is_error": None, "details": None}
    assert tool["streaming"] is False
    assert items[5]["result"] is None and items[5]["streaming"] is False
    assert len({i["id"] for i in items}) == len(items)


def test_user_text_blocks_become_user_item():
    builder = ConversationBuilder()
    builder.load_history([user_entry([{"type": "text", "text": "olá"}, {"type": "image"}])])
    items = builder.snapshot()
    assert len(items) == 1 and items[0]["text"] == "olá"


def test_orphan_tool_result_is_ignored():
    builder = ConversationBuilder()
    builder.load_history([user_entry([{"type": "tool_result", "tool_use_id": "x", "content": "a"}])])
    assert builder.snapshot() == []


def test_unknown_entries_are_ignored():
    builder = ConversationBuilder()
    builder.load_history([
        assistant_entry({"type": "weird"}, "m1"),
        user_entry(None),
    ])
    assert builder.snapshot() == []


# Real-format details ------------------------------------------------------


def tool_use(tool_id: str, name: str = "Bash") -> dict:
    return {"type": "tool_use", "id": tool_id, "name": name, "input": {}}


def test_parallel_tool_results_come_from_the_raw_file():
    # get_session_messages follows one parentUuid chain: parallel results are lost.
    entries = [
        user_entry("faça"),
        assistant_entry(tool_use("t1"), "m1"),
        assistant_entry(tool_use("t2", "Edit"), "m1"),
        user_entry([{"type": "tool_result", "tool_use_id": "t2", "content": "b"}]),
    ]
    raw = {
        "t1": {"content": "a", "is_error": False, "details": {"stdout": "a"}},
        "t2": {"content": "b", "is_error": False, "details": {"structuredPatch": []}},
    }
    builder = ConversationBuilder()

    builder.load_history(entries, raw)

    tools = [i for i in builder.snapshot() if i["type"] == "tool"]
    assert tools[0]["result"] == {"content": "a", "is_error": False, "details": {"stdout": "a"}}
    assert tools[1]["result"]["details"] == {"structuredPatch": []}
    assert all(t["result_missing"] is False for t in tools)


def test_tool_without_any_result_is_marked_missing():
    builder = ConversationBuilder()
    builder.load_history([assistant_entry(tool_use("t1"), "m1")], {})
    tool = builder.snapshot()[0]
    assert tool["result"] is None
    assert tool["result_missing"] is True
    assert tool["streaming"] is False


def test_cli_tags_become_notices_or_are_dropped():
    builder = ConversationBuilder()
    builder.load_history([
        user_entry("<command-name>/commit</command-name>\n<command-message>commit</command-message>"
                   "\n<command-args></command-args>"),
        user_entry("<local-command-stdout>saída do comando</local-command-stdout>"),
        user_entry("<task-notification><task-id>x</task-id></task-notification>"),
        user_entry([{"type": "text", "text": "[Request interrupted by user]"}]),
        user_entry([{"type": "text", "text": "[Request interrupted by user for tool use]"}]),
        user_entry("Caveat: The messages below were generated by the user"),
        user_entry([
            {"type": "text", "text": "<system-reminder>lembrete</system-reminder>"},
            {"type": "text", "text": "pergunta normal"},
        ]),
    ])
    items = builder.snapshot()
    assert [(i["type"], i["text"]) for i in items] == [
        ("user", "/commit"),
        ("notice", "saída do comando"),
        ("notice", "Subagente em segundo plano terminou"),
        ("notice", "Interrompido."),
        ("notice", "Interrompido."),
        ("user", "pergunta normal"),
    ]
    assert all(i["level"] == "info" for i in items if i["type"] == "notice")


def test_command_with_arguments_becomes_the_user_bubble():
    builder = ConversationBuilder()
    builder.load_history([
        user_entry("<command-message>hello</command-message>\n<command-name>/hello</command-name>"
                   "\n<command-args>Vinicius</command-args>"),
    ])
    assert [(i["type"], i["text"]) for i in builder.snapshot()] == [("user", "/hello Vinicius")]


def test_builtin_command_output_is_still_a_notice():
    builder = ConversationBuilder()
    builder.load_history([
        user_entry("<command-name>/model</command-name>\n<command-message>model</command-message>"
                   "\n<command-args></command-args>"),
        user_entry("<local-command-stdout>Set model to haiku</local-command-stdout>"),
    ])
    assert [(i["type"], i["text"]) for i in builder.snapshot()] == [
        ("user", "/model"),
        ("notice", "Set model to haiku"),
    ]


def test_user_images_and_documents_become_light_markers():
    builder = ConversationBuilder()
    builder.load_history([
        user_entry([
            {"type": "image", "source": {"type": "base64", "media_type": "image/png",
                                         "data": "A" * 400}},
            {"type": "document", "source": {"type": "base64", "media_type": "application/pdf",
                                            "data": "B" * 40}},
        ]),
    ])
    items = builder.snapshot()
    assert len(items) == 1 and items[0]["type"] == "user"
    assert items[0]["text"] == ""
    assert items[0]["images"] == [
        {"type": "image", "media_type": "image/png", "size": 300},
        {"type": "document", "media_type": "application/pdf", "size": 30},
    ]
    assert "AAAA" not in str(items)


def test_tool_result_images_are_omitted():
    screenshot = {"type": "image", "source": {"type": "base64", "media_type": "image/jpeg",
                                              "data": "Z" * 1000}}
    builder = ConversationBuilder()
    builder.load_history(
        [
            assistant_entry(tool_use("t1", "Screenshot"), "m1"),
            user_entry([{"type": "tool_result", "tool_use_id": "t1",
                         "content": [{"type": "text", "text": "ok"}, screenshot]}]),
            assistant_entry(tool_use("t2", "Screenshot"), "m1"),
        ],
        {"t2": {"content": [screenshot], "is_error": False, "details": None}},
    )
    tools = builder.snapshot()
    assert tools[0]["result"]["content"] == [
        {"type": "text", "text": "ok"},
        {"type": "image", "omitted": True, "media_type": "image/jpeg"},
    ]
    assert tools[1]["result"]["content"] == [
        {"type": "image", "omitted": True, "media_type": "image/jpeg"}
    ]
    assert "ZZZ" not in str(tools)


def test_empty_and_redacted_thinking_are_dropped():
    builder = ConversationBuilder()
    builder.load_history([
        assistant_entry({"type": "thinking", "thinking": "", "signature": "s"}, "m1"),
        assistant_entry({"type": "redacted_thinking", "data": "x"}, "m1"),
        assistant_entry({"type": "thinking", "thinking": "real", "signature": "s"}, "m1"),
    ])
    assert [i["text"] for i in builder.snapshot()] == ["real"]


# Size limits ---------------------------------------------------------------

from claudio_maestro.conversation import cap_content, slim_details  # noqa: E402


def test_edit_details_keep_patch_only():
    details = {"filePath": "a.py", "structuredPatch": [{"lines": ["+x"]}], "type": "update",
               "userModified": False, "originalFile": "x" * 10, "content": "y",
               "oldString": "o", "newString": "n"}
    for name in ("Edit", "MultiEdit", "Write"):
        assert slim_details(name, details) == {
            "filePath": "a.py", "structuredPatch": [{"lines": ["+x"]}], "type": "update",
            "userModified": False,
        }


def test_read_details_keep_path_and_counts():
    details = {"type": "text", "file": {"filePath": "a.py", "content": "abc", "numLines": 3,
                                        "startLine": 1, "totalLines": 9}}
    assert slim_details("Read", details) == {
        "type": "text", "file": {"filePath": "a.py", "numLines": 3, "startLine": 1, "totalLines": 9}
    }


def test_other_details_cut_long_strings():
    details = {"stdout": "a" * 20_005, "nested": [{"s": "b" * 10}], "n": 1}
    slim = slim_details("Bash", details)
    assert slim["stdout"] == "a" * 20_000 + "…[cortado 5 caracteres]"
    assert slim["nested"] == [{"s": "b" * 10}] and slim["n"] == 1
    assert slim_details("Bash", None) is None
    assert slim_details("Bash", "texto") == "texto"


def test_result_content_is_capped():
    assert cap_content("c" * 200_010) == "c" * 200_000 + "…[cortado 10 caracteres]"
    capped = cap_content([{"type": "text", "text": "d" * 200_001}])
    assert capped[0]["text"].endswith("…[cortado 1 caracteres]")


def test_limits_apply_to_history_and_live():
    from claude_agent_sdk import ToolResultBlock, ToolUseBlock, UserMessage

    raw = {"t1": {"content": "e" * 200_003, "is_error": False,
                  "details": {"filePath": "f", "originalFile": "big"}}}
    builder = ConversationBuilder()
    builder.load_history([assistant_entry(tool_use("t1", "Edit"), "m1")], raw)
    result = builder.snapshot()[0]["result"]
    assert result["details"] == {"filePath": "f"}
    assert len(result["content"]) < 200_100

    live = ConversationBuilder()
    live._apply_block(ToolUseBlock(id="t2", name="Edit", input={}), "m:0", None)
    live.handle(UserMessage(
        content=[ToolResultBlock(tool_use_id="t2", content="ok")],
        tool_use_result={"filePath": "f", "originalFile": "big", "structuredPatch": []},
    ))
    assert live.snapshot()[0]["result"]["details"] == {"filePath": "f", "structuredPatch": []}
