"""Contract between the app and the agent: options, client protocol, errors.

The real implementation lives in `sdk_client.py`; tests use `fake.py`.
"""

from collections.abc import AsyncIterator, Awaitable, Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Protocol, runtime_checkable

from claude_agent_sdk import (
    Message,
    PermissionResultAllow,
    PermissionResultDeny,
    ToolPermissionContext,
)

PermissionCallback = Callable[
    [str, dict[str, Any], ToolPermissionContext],
    Awaitable[PermissionResultAllow | PermissionResultDeny],
]


class AgentError(Exception):
    """Agent failure with a message ready to show to the user (pt-BR).

    `session_in_use` marks a connect that failed because the session id already
    exists on disk (it must be resumed, not started again).
    `refused` marks a control request (model or mode change) the agent answered
    with an error while its process is alive; `message_pt` then holds the agent's
    own text. Any other failure means the client is gone.
    """

    def __init__(
        self, message_pt: str, *, session_in_use: bool = False, refused: bool = False
    ) -> None:
        super().__init__(message_pt)
        self.message_pt = message_pt
        self.session_in_use = session_in_use
        self.refused = refused


@dataclass
class AgentOptions:
    cwd: Path
    session_id: str  # UUID generated by the app
    resume: bool  # False: new session, passes session_id. True: passes resume=session_id
    can_use_tool: PermissionCallback
    model: str | None = None
    effort: str | None = None  # "low" | "medium" | "high" | "xhigh" | "max"
    permission_mode: str | None = None  # "default" | "acceptEdits" | "plan" | "bypassPermissions" | "auto" | "dontAsk"
    # None: SDK default (user, project and local settings, hooks and plugins load).
    # []: none of them, for throwaway clients that only query the CLI.
    setting_sources: list[str] | None = None


@runtime_checkable
class AgentClient(Protocol):
    async def connect(self) -> None: ...

    async def send(self, content: str | list[dict[str, Any]]) -> None: ...

    def messages(self) -> AsyncIterator[Message]:
        """Continuous stream of SDK messages until close(). Raises AgentError on failure."""
        ...

    async def interrupt(self) -> None: ...

    async def stop_task(self, task_id: str) -> None:
        """Stop a background task (e.g. a subagent) by the id of its task messages."""
        ...

    async def set_model(self, model: str | None) -> None: ...

    async def set_permission_mode(self, mode: str) -> None: ...

    async def get_server_info(self) -> dict[str, Any] | None:
        """Initialization info of the CLI; `models` lists the available models."""
        ...

    async def get_context_usage(self) -> dict[str, Any] | None:
        """Context window usage (`/context`): `totalTokens`, `rawMaxTokens`, `maxTokens`, `percentage`."""
        ...

    async def close(self) -> None: ...


AgentFactory = Callable[[AgentOptions], AgentClient]
